name: Classify Strava Activities

on:
  schedule:
    - cron: "*/10 * * * *"  # Alle 10 Minuten
  workflow_dispatch:       # Manuelles Triggern per GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run classify script
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python classify_activities/classify.py

